### ISSUE TITLE
Version check crashes on Kart development builds

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart-qgis-plugin#36]
Trigger: context menu, Refresh on a repository.
```
ValueError: too many values to unpack (expected 3) 
Traceback (most recent call last):
  File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 143, in wrapper
    f(*args)
  File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 170, in refreshContent
    self.populate()
  File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 283, in populate
    self.datasetsItem = DatasetsItem(self.repo)
  File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 539, in __init__
    self.populate()
  File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/kartapi.py", line 49, in inner
    if checkKartInstalled():
  File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/kartapi.py", line 101, in checkKartInstalled
    major, minor, patch = version.split(".")
ValueError: too many values to unpack (expected 3)
```

* my Kart version (local dev install): `v0.10.7.dev0`
* Non-release CI build artifacts have versioning along these lines: `v0.10.7.dev0+ci.2922.git93c7eded`

Note that dev builds `X.Y.Z.dev0` refers to the _next_ patch release number (ie. `X.Y.(Z+1)` from the latest release). I think for the purposes of the QGIS plugin check we ignore anything after the patch number.

**Comment by volaya** [comment]
This should be fixed already
