### ISSUE TITLE
Ask for confirmation before performing certain operations

### ISSUE THREAD

**Issue by volaya** [koordinates/kart-qgis-plugin#46]
Such as discarding changes, removing repos, etc

**Comment by rcoup** [comment]
Removing a repo I get

```
2021-12-14T12:58:41     WARNING    Traceback (most recent call last):
              File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 143, in wrapper
              f(*args)
              File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 341, in removeRepository
              if confirm("Are you sure you want to remove this repository?"):
              File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/utils.py", line 54, in confirm
              ret = QMessageBox.warning("Kart", msg, QMessageBox.Yes | QMessageBox.No)
             TypeError: warning(QWidget, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'str'
             
```

**Comment by volaya** [comment]
Fixed
