### ISSUE TITLE
Cloning fails looking for repo description

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart-qgis-plugin#47]
Kart plugin log
```
2021-12-14T12:26:46     INFO    Command: /Users/rcoup/code/kart/build/venv/bin/kart -vv clone kart@example.com:nz-land-districts /Users/rcoup/Downloads/nz-land-districts-2 --progress
2021-12-14T12:26:54     INFO    Command output: Creating working copy at nz-land-districts-2.gpkg ...
```             
Python error log
```
2021-12-14T12:21:56     WARNING    Traceback (most recent call last):
              File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 143, in wrapper
              f(*args)
              File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/kartapi.py", line 51, in inner
              return f(*args)
              File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 255, in cloneRepo
              item = RepoItem(repo)
              File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 264, in __init__
              self.setTitle()
              File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 278, in setTitle
              f"{self.repo.title() or os.path.normpath(self.repo.path)} "
              File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/kartapi.py", line 311, in title
              with open(os.path.join(self.path, ".kart", "description")) as f:
             FileNotFoundError: [Errno 2] No such file or directory: '~/tmp/nz-land-districts/.kart/description'
```

**Comment by rcoup** [comment]
Ah, and the half-cloned repo seems to be persisted in QGIS, I get the same error after a restart, even though it doesn't appear in the Repositories panel
