### ISSUE TITLE
Error when pushing changes to remote repository

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/kart-qgis-plugin#54]
**Description**

Attempting to push commits to a remote repository results in an error, and commits are not pushed. QGIS error reported as follows:

```
An error has occurred while executing Python code: 

TypeError: cannot unpack non-iterable builtin_function_or_method object 
Traceback (most recent call last):
  File "/Users/hamish/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 147, in wrapper
    f(*args)
  File "/Users/hamish/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/kartapi.py", line 51, in inner
    return f(*args)
  File "/Users/hamish/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 530, in push
    remote, branch, pushall = dialog.result
TypeError: cannot unpack non-iterable builtin_function_or_method object


Python version: 3.8.7 (default, May 24 2021, 13:02:34) [Clang 12.0.5 (clang-1205.0.22.9)] 
QGIS version: 3.20.0-Odense Odense, decaadbb31 
```

The equivalent call to `kart push` succeeds.

**To Reproduce**

1. Clone a repository by URL
2. Commit a change locally
3. Attempt to push by right-clicking the repository and pressing "push"

**Expected behavior**

Commits are successfully pushed to the remote location.

**Version info**

```
Kart Plugin version
1.0.1

QGIS version
3.20.0-Odense

Operating system
macOS 12.0.1 x86_64 i386 64bit

Kart version
Kart v0.10.7, Copyright (c) Kart Contributors
» GDAL v3.3.2; PROJ v6.3.0
» PyGit2 v1.7.0; Libgit2 v1.3.0; Git v2.33.GIT
» SQLAlchemy v1.4.11; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.1; Libpq v14.0.1
» SpatialIndex v1.9.3
```

**Comment by hamishcampbell** [comment]
Confirmed this happens on Windows too.
