### ISSUE TITLE
ValueError: too many values to unpack (expected 2) 

### ISSUE THREAD

**Issue by bismarksr17** [koordinates/kart-qgis-plugin#74]
![image_2022-08-23_155102417](https://user-images.githubusercontent.com/48069354/186253058-bd247406-6142-4e1a-a29f-f44d19f137ad.png)
When I enter in...

Show Logs > Show changes introduced by this commit...

the following error is displayed

An error has occurred while executing Python code: 

ValueError: too many values to unpack (expected 2) 
Traceback (most recent call last):
  File "C:\Users/UTEA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\gui\diffviewer.py", line 182, in treeItemChanged
    self._createLayers()
  File "C:\Users/UTEA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\gui\diffviewer.py", line 458, in _createLayers
    self._createFeatureDiffLayers()
  File "C:\Users/UTEA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\gui\diffviewer.py", line 513, in _createFeatureDiffLayers
    self._createVertexDiffLayer(geoms)
  File "C:\Users/UTEA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\gui\diffviewer.py", line 557, in _createVertexDiffLayer
    x, y = coord.strip().split(" ")
ValueError: too many values to unpack (expected 2)

I work with QGIS 3.22.10 and Kart 0.11.3

Thank you!

**Comment by pfw** [comment]
This issue is understood and a new release of the plugin will be available very shortly.

**Comment by pfw** [comment]
@bismarksr17 There is a new build of the plugin available at https://github.com/koordinates/kart-qgis-plugin/actions/runs/2916898389 which can be installed directly from the kart_package.zip. If that works for you we can get that fix into a release installable directly via QGIS plugin manager.

**Comment by rcoup** [comment]
Release in 1.0.3 which is now in the QGIS plugin manager.
