### ISSUE TITLE
Exception loading layers from postgis repository if port was specified in connection dialog

### ISSUE THREAD

**Issue by enricofer** [koordinates/kart-qgis-plugin#89]
**Describe the bug**
working with postgis database specifiyng a port in repository connection dialog (even if 5432)
Loading a layer throws the following exception:

**To Reproduce**
1. add a postgis repository specifyng a port, even if 5432 (leaving blank the port the default value "5432" will be used and no exception will be raised)
2. Add a new layer to project from the repository
4. See error:
TypeError: QgsDataSourceUri.setConnection(): arguments did not match any overloaded call:   overload 1: argument 2 has unexpected type 'int'   overload 2: argument 2 has unexpected type 'int' 
Traceback (most recent call last):
  File "C:\Users/ferregutie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\gui\dockwidget.py", line 158, in wrapper
    f(*args)
  File "C:\Users/ferregutie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\gui\dockwidget.py", line 747, in addToProject
    layer = self.repo.workingCopyLayer(self.name)
  File "C:\Users/ferregutie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\kartapi.py", line 752, in workingCopyLayer
    uri.setConnection(host, port, database, username, password)
TypeError: QgsDataSourceUri.setConnection(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'int'
  overload 2: argument 2 has unexpected type 'int'

I provide a patch to solve it: https://github.com/enricofer/kart-qgis-plugin/tree/dbport-as-string-patch

**Comment by rcoup** [comment]
Fixed in #90
